version: '3'
services:

# --------  Worker [1]  -------- #
  worker_1:
    build: './murtazo_worker'
    user: root
    
# --------  Worker [2]  -------- #
  worker_2:
    build: './murtazo_worker'
    user: root
