version: '3'
services:

# --------  Worker [1]  -------- #
  worker_1:
    build: './murtazo_worker'
    user: root
    
# --------  Worker [2]  -------- #
  worker_2:
    build: './murtazo_worker'
    user: root
    
# --------  Worker [3]  -------- #
  worker_3:
    build: './murtazo_worker'
    user: root    
    
# --------  Worker [4]  -------- #
  worker_4:
    build: './murtazo_worker'
    user: root
